# Generated by Django 3.2 on 2023-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valid_phone',
            field=models.BooleanField(default=False, help_text='Designates whether the user has valid phone number.', verbose_name='phone valid'),
        ),
    ]
