# Generated by Django 3.2 on 2023-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbook',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
