# Generated by Django 3.2 on 2023-04-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskbook_expired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasks',
        ),
    ]
